substitutions:
  project_version: "dev"
  display_rows: "3"
  pinned_rows_max: "2"

esphome:
  name: transit-tracker
  friendly_name: Transit Tracker
  name_add_mac_suffix: true
  min_version: 2026.1.4
  project:
    name: "Eastside Urbanism.Transit Tracker"
    version: ${project_version}

esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: arduino

external_components:
  - source: github://pr#13921
    components: [ hub75 ]
    refresh: 1h
  - source: github://tjhorner/esphome-custom-components@c57ffd46fcf30badb2838421e8ff6cbeb9c1dd06
    components: [ serial_rpc, lis3dh, project_version ]
  - source:
      type: local
      path: C:/Users/sfent/source/repos/esphome-transit-tracker/components

logger:
  level: DEBUG
  logs:
    mqtt: WARN
    mqtt.component: WARN
    mqtt.client: WARN
    api: WARN
    api.connection: WARN
    wifi: WARN
    sensor: WARN
    text_sensor: WARN
    switch: WARN
    number: WARN
    select: WARN
    text: WARN
    component: WARN

wifi:
  ap:
    password: "hunter2hunter2"

captive_portal:

api:
  reboot_timeout: 0s

mqtt:
  broker: !secret mqtt_broker
  discovery: false  # We handle our own discovery for route switches

http_request:
  verify_ssl: false

ota:
  - platform: http_request
  - platform: esphome
    password: ""

update:
  - platform: http_request
    name: Firmware Update
    source: https://transit-tracker.eastsideurbanism.org/firmware/manifest.json

switch:
  - platform: template
    id: flip_display_config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - lambda: |-
          id(matrix).set_rotation(esphome::display::DisplayRotation::DISPLAY_ROTATION_180_DEGREES);
    on_turn_off:
      - lambda: |-
          id(matrix).set_rotation(esphome::display::DisplayRotation::DISPLAY_ROTATION_0_DEGREES);
  - platform: template
    id: scroll_headsigns_config
    name: "Scroll Headsigns"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - lambda: id(tracker).set_scroll_headsigns(true);
    on_turn_off:
      - lambda: id(tracker).set_scroll_headsigns(false);
  - platform: template
    id: uniform_headsign_start_config
    name: "Uniform Headsign Start"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - lambda: id(tracker).set_uniform_headsign_start(true);
    on_turn_off:
      - lambda: id(tracker).set_uniform_headsign_start(false);
  - platform: template
    id: uniform_headsign_end_config
    name: "Uniform Headsign End"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - lambda: id(tracker).set_uniform_headsign_end(true);
    on_turn_off:
      - lambda: id(tracker).set_uniform_headsign_end(false);
  - platform: template
    id: show_pin_icon_config
    name: "Show Pin Icon"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - lambda: id(tracker).set_show_pin_icon(true);
    on_turn_off:
      - lambda: id(tracker).set_show_pin_icon(false);
  - platform: template
    id: respect_pin_inset_config
    name: "Respect Pin Inset"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - lambda: id(tracker).set_respect_pin_inset(true);
    on_turn_off:
      - lambda: id(tracker).set_respect_pin_inset(false);
  - platform: template
    id: scroll_routes_config
    name: "Scroll Routes"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - lambda: id(tracker).set_scroll_routes(true);
    on_turn_off:
      - lambda: id(tracker).set_scroll_routes(false);
  - platform: template
    id: always_scroll_or_replace_config
    name: "Always Scroll or Replace"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - lambda: id(tracker).set_always_scroll_or_replace(true);
    on_turn_off:
      - lambda: id(tracker).set_always_scroll_or_replace(false);

number:
  - platform: template
    id: page_interval_config
    name: "Page Interval"
    optimistic: true
    restore_value: true
    initial_value: 5
    min_value: 5
    max_value: 60
    step: 1
    unit_of_measurement: "s"
    on_value:
      then:
        lambda: |-
          id(tracker).set_page_interval((int)x);
  - platform: template
    id: page_scroll_duration_config
    name: "Page Scroll Duration"
    optimistic: true
    restore_value: true
    initial_value: 0.5
    min_value: 0.5
    max_value: 3.0
    step: 0.1
    unit_of_measurement: "s"
    on_value:
      then:
        lambda: |-
          id(tracker).set_page_scroll_duration(x);
  - platform: template
    id: page_pause_duration_config
    name: "Page Pause Duration"
    optimistic: true
    restore_value: true
    initial_value: 1
    min_value: 1
    max_value: 5
    step: 1
    unit_of_measurement: "s"
    on_value:
      then:
        lambda: |-
          id(tracker).set_page_pause_duration((int)x);
  - platform: template
    id: pinned_rows_count_config
    name: "Pinned Rows Count"
    optimistic: true
    restore_value: true
    initial_value: 1
    min_value: 1
    max_value: ${pinned_rows_max}
    step: 1
    on_value:
      then:
        lambda: |-
          id(tracker).set_pinned_rows_count((int)x);

button:
  - platform: restart
    name: "Restart"
  - platform: template
    id: reload_tracker
    on_press:
      - lambda: |-
          id(tracker).reconnect();
  - platform: template
    id: write_preferences
    on_press:
      - lambda: |-
          global_preferences->sync();

text:
  - &config_text_common
    platform: template
    id: base_url_config
    mode: text
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: |
          id(tracker).set_base_url(id(base_url_config)->state);
  - <<: *config_text_common
    id: feed_code_config
    on_value:
      then:
        lambda: |
          id(tracker).set_feed_code(id(feed_code_config)->state);
  - <<: *config_text_common
    id: schedule_config
    on_value:
      then:
        lambda: |
          id(tracker).set_schedule_string(id(schedule_config)->state);
  - <<: *config_text_common
    id: abbreviations_config
    on_value:
      then:
        lambda: |
          id(tracker).set_abbreviations_from_text(id(abbreviations_config)->state);
  - <<: *config_text_common
    id: route_styles_config
    on_value:
      then:
        lambda: |
          id(tracker).set_route_styles_from_text(id(route_styles_config)->state);
  - <<: *config_text_common
    id: hidden_routes_config
    name: "Hidden Routes"
    internal: true
    on_value:
      then:
        lambda: |
          id(tracker).set_hidden_routes_from_text(id(hidden_routes_config)->state);
  - <<: *config_text_common
    id: pinned_routes_config
    name: "Pinned Routes"
    internal: true
    on_value:
      then:
        lambda: |
          id(tracker).set_pinned_routes_from_text(id(pinned_routes_config)->state);
  - <<: *config_text_common
    id: next_only_routes_config
    name: "Next Only Routes"
    internal: true
    on_value:
      then:
        lambda: |
          id(tracker).set_next_only_routes_from_text(id(next_only_routes_config)->state);
  - <<: *config_text_common
    id: now_str_config
    initial_value: "min"
    on_value:
      then:
        lambda: |-
          id(tracker).get_localization()->set_now_string(id(now_str_config)->state);
  - <<: *config_text_common
    id: min_long_str_config
    initial_value: "min"
    on_value:
      then:
        lambda: |-
          id(tracker).get_localization()->set_minutes_long_string(id(min_long_str_config)->state);
  - <<: *config_text_common
    id: min_short_str_config
    initial_value: "m"
    on_value:
      then:
        lambda: |-
          id(tracker).get_localization()->set_minutes_short_string(id(min_short_str_config)->state);
  - <<: *config_text_common
    id: hours_short_str_config
    initial_value: "h"
    on_value:
      then:
        lambda: |-
          id(tracker).get_localization()->set_hours_short_string(id(hours_short_str_config)->state);
  - <<: *config_text_common
    id: route_color_overrides_config
    on_value:
      then:
        lambda: |-
          id(tracker).set_route_color_overrides_from_text(id(route_color_overrides_config)->state);

select:
  - platform: template
    id: time_display_config
    optimistic: true
    restore_value: true
    options:
      - "departure"
      - "arrival"
    on_value:
      then:
        lambda: |-
          id(tracker).set_display_departure_times(id(time_display_config)->current_option() == "departure");
  - platform: template
    id: time_units_config
    optimistic: true
    restore_value: true
    options:
      - "long"
      - "short"
      - "none"
    on_value:
      then:
        lambda: |-
          transit_tracker::UnitDisplay unit_display;
          if (id(time_units_config)->current_option() == "long") {
            unit_display = transit_tracker::UnitDisplay::UNIT_DISPLAY_LONG;
          } else if (id(time_units_config)->current_option() == "short") {
            unit_display = transit_tracker::UnitDisplay::UNIT_DISPLAY_SHORT;
          } else {
            unit_display = transit_tracker::UnitDisplay::UNIT_DISPLAY_NONE;
          }

          id(tracker).set_unit_display(unit_display);
  - platform: template
    id: list_mode_config
    optimistic: true
    restore_value: true
    options:
      - "sequential"
      - "nextPerRoute"
    on_value:
      then:
        lambda: |-
          id(tracker).set_list_mode(id(list_mode_config)->current_option());
  - platform: template
    id: scroll_speed_config
    name: "Scroll Speed"
    optimistic: true
    restore_value: true
    options:
      - "slow"
      - "medium"
      - "fast"
    initial_option: "medium"
    on_value:
      then:
        lambda: |-
          id(tracker).set_scroll_speed(id(scroll_speed_config)->current_option());

output:
  - platform: template
    id: display_brightness_output
    type: float
    min_power: 0.004 # 1/255
    zero_means_zero: true
    write_action:
      - hub75.set_brightness:
          id: matrix
          brightness: !lambda return state * 255.0;

light:
  - platform: monochromatic
    name: Display Brightness
    id: display_brightness
    output: display_brightness_output
    restore_mode: RESTORE_DEFAULT_ON

status_led:
  pin:
    number: GPIO13

script:
  - id: dim_display
    parameters:
      up: bool
    then:
      - light.dim_relative:
          id: display_brightness
          relative_brightness: !lambda "return up ? 0.2 : -0.2;"
          transition_length: 0.1s

binary_sensor:
  - platform: template
    id: both_buttons
    lambda: |-
      return id(up_button).state && id(down_button).state;
    on_press:
      then:
        - display.page.show_next: matrix
  - platform: gpio
    id: up_button
    pin: &button_pin_cfg
      number: GPIO6
      inverted: true
      mode:
        input: true
        pullup: true
    filters: &button_filters
      - autorepeat:
        - delay: 500ms
          time_off: 300ms
          time_on: 100ms
    on_press:
      then:
        - script.execute:
            id: dim_display
            up: !lambda "return !id(flip_display_config).state;"
  - platform: gpio
    id: down_button
    pin:
      <<: *button_pin_cfg
      number: GPIO7
    filters: *button_filters
    on_press:
      then:
        - script.execute:
            id: dim_display
            up: !lambda "return id(flip_display_config).state;"

i2c:
  sda: GPIO16
  scl: GPIO17

lis3dh:
  range: 2G
  data_rate: 1HZ
  resolution: HIGH_RES
  address: 0x19
  update_interval: 1s

text_sensor:
  - platform: project_version
    id: project_version_text
  - platform: lis3dh
    orientation_xy:
      id: orientation_sensor
      on_value:
        then:
          - if:
              condition:
                lambda: |-
                  return x == "Portrait Upside Down";
              then:
                - switch.turn_on: flip_display_config
          - if:
              condition:
                lambda: |-
                  return x == "Portrait Upright";
              then:
                - switch.turn_off: flip_display_config

sensor:
  - platform: uptime
    type: timestamp
    name: Uptime

display:
  - platform: hub75
    id: matrix
    board: adafruit-matrix-portal-s3
    double_buffer: true
    update_interval: 32ms
    panel_width: 64
    panel_height: 32
    layout_cols: 2
    # We swap the G and B channels in firmware because the 64x32 panel hardware has them reversed
    g1_pin: 40
    b1_pin: 41
    g2_pin: 37
    b2_pin: 39
    e_pin: 21
    brightness: 255
    pages:
      - id: transit_schedule
        lambda: |-
          id(tracker).draw_schedule();
      - id: ip_address_page
        lambda: |-
          int x = it.get_width() / 2;
          int y = it.get_height() / 2;

          auto ip_addresses = ::esphome::network::get_ip_addresses();
          if (ip_addresses.empty()) {
            it.printf(x, y, id(pixolletta), COLOR_ON, TextAlign::CENTER, "No IP Address");
            return;
          }

          it.printf(x, y, id(pixolletta), COLOR_ON, TextAlign::CENTER, "%s", ip_addresses[0].str().c_str());

font:
  - file: "fonts/Pixolletta8px.ttf"
    id: pixolletta
    size: 10
    glyphs:
      - abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,:;!?()"'-+/*=%@#[]{}<>|&^~
      - ÄËÏÖÜÉÈÔäëïöüéèôŊŋÁÊÎÛÝáêîûýĜĝÀÌÒàìòÑñÍÓÚíóúÇçĆČĐŠŽćčđšžÙùÕõŞŁŇŘşłňřÅåØøĀĒĪŌŪāēīōūÂâĞğıĎĚŤŮďěťůÆæĲĳŒœÐðŸÿßŐŰőűÞþÃãĂĔĬŎŬăĕĭŏŭĨŨĩũĄĘŃŚŻąęńśżĖėĢĶĻŅģķļņĮŲįųŔŹŕźĊĠċġħŜŝŢţŦŧŴŵŶŷĹĽĺľİ
      - " "

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Los_Angeles

web_server:

transit_tracker:
  id: tracker
  limit: ${display_rows}
  hidden_routes_text: hidden_routes_config
  pinned_routes_text: pinned_routes_config
  next_only_routes_text: next_only_routes_config
  route_color_overrides_text: route_color_overrides_config

serial_rpc:
